import { twMerge } from 'tailwind-merge'
import './globals.css'
import { Montserrat } from 'next/font/google'

const monserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={twMerge(monserrat.className, "bg-gray-100")}>{children}</body>
    </html>
  )
}
